;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/_ConnectIt/_Framework/Game/ConnectIt_GameplayTags.ConnectIt_GameplayTags
+GameplayTagRedirects=(OldTagName="ConnectIt.State.Game.Start",NewTagName="ConnectIt.State.Game.Begin")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="ConnectIt.State.Game.Begin",DevComment="")
+GameplayTagList=(Tag="ConnectIt.State.Game.End",DevComment="")
+GameplayTagList=(Tag="ConnectIt.State.PostGame",DevComment="")
+GameplayTagList=(Tag="ConnectIt.State.PreGame",DevComment="")

